#!/bin/bash

# Put this file at: .git/hooks/post-checkout and make it executable

file="composer.lock"

if [[ $(git diff HEAD@{1}..HEAD@{0} -- "${file}" | wc -l) -gt 0 ]]; then
    echo
    echo "NB : '${file}' changed, executing 'composer install'"
    echo
    composer install
    echo
fi
