#!/bin/bash

# Put this file at: .git/hooks/post-checkout and make it executable

readonly PREV_COMMIT=$1
readonly POST_COMMIT=$2

[[ '0000000000000000000000000000000000000000' == "$PREV_COMMIT" ]] && exit 0

readonly NOCOLOR='\e[0m'
readonly REDCOLOR='\e[37;41m'

if [[ -f composer.lock ]]; then
    [[ $(git diff --shortstat $PREV_COMMIT..$POST_COMMIT composer.lock) != "" ]] && echo -e "$REDCOLOR composer.lock has changed. You must run composer install$NOCOLOR"
fi

if [[ -f package.json ]]; then
    [[ $(git diff --shortstat $PREV_COMMIT..$POST_COMMIT package.json) != "" ]] && echo -e "$REDCOLOR package.json has changed. You must run npm install$NOCOLOR"
fi

if [[ -f yarn.lock ]]; then
    [[ $(git diff --shortstat $PREV_COMMIT..$POST_COMMIT yarn.lock) != "" ]] && echo -e "$REDCOLOR yarn.lock has changed. You must run yarn$NOCOLOR"
fi

if [[ -f chef/Cheffile.lock ]]; then
    [[ $(git diff --shortstat $PREV_COMMIT..$POST_COMMIT chef/Cheffile.lock) != "" ]] && echo -e "$REDCOLOR chef/Cheffile.lock has changed. You must run librarian-chef install$NOCOLOR"
fi
