#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# in .git/hooks/post-checkout
# and make it executable
# You can install it system wide too, see http://stackoverflow.com/a/2293578/685587

PREV_COMMIT=$1
POST_COMMIT=$2

NOCOLOR='\x1B[0m'
REDCOLOR='\x1B[37;41m'

if [[ -f composer.lock ]]; then
    DIFF=`git diff --shortstat $PREV_COMMIT..$POST_COMMIT composer.lock`
    if [[ $DIFF != "" ]]; then
        echo -e "$REDCOLOR composer.lock has changed. You must run composer install$NOCOLOR"
    fi
fi

if [[ -f app/console ]]; then
    php app/console doctrine:schema:update --dump-sql
fi
