#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# in .git/hooks/pre-commit
# and make it executable
# You can install it system wide too, see http://stackoverflow.com/a/2293578/685587

# Search your sourcecode for forbidden code
FORBIDDEN='var_dump'
git diff --cached --name-only | \
    grep -E '\.(php)(\..+)?$' | \
    GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n $FORBIDDEN && echo 'COMMIT REJECTED Found "$FORBIDDEN" references. Please remove them before commiting' && exit 1


# PHP linter
php_files=$(git status --short | grep -E '^(A|M)' | awk '{ print $2 }' | grep -E '\.php$')

for file in $php_files; do
    php_out=$(php -l "$file" 2>&1)

    if ! [ $? -eq 0 ]; then
        echo "Syntax error with ${file}:"
        echo "$php_out" | grep -E '^Parse error'
        echo
    fi
done
