#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# in .git/hooks/pre-commit
# and make it executable
# You can install it system wide too, see http://stackoverflow.com/a/2293578/685587

# Search your sourcecode for var-dumps
FILES_PATTERN='\.(php)(\..+)?$'
FORBIDDEN='var_dump'
git diff --cached --name-only | \
grep -E $FILES_PATTERN | \
GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n $FORBIDDEN && echo 'COMMIT REJECTED Found "$FORBIDDEN" references. Please remove them before commiting' && exit 1


# PHP linter
git diff --cached --name-status --diff-filter=ACMR | while read STATUS FILE; do
    if [[ "$FILE" =~ ^.+(php|inc)$ ]]; then
        php -l "$FILE" 1> /dev/null
        if [ $? -ne 0 ]; then
            echo "Aborting commit due to files with syntax errors" >&2
            exit 1
        fi
    fi
done
